<a href="https://colab.research.google.com/github/Tikakiku/MachineLearningTasks/blob/main/UAS/Ratika_Dwi_Anggraini_00_Pytorch_Fundamentals_UAS_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

####UAS Machine Learning
####Technical Report on Github (https://github.com/Tikakiku/MachineLearningTasks)
#####Nama : Ratika Dwi Anggraini
#####NIM : 1103201250


# 00. PyTorch Fundamentals

# Apa itu PyTorch?

[PyTorch](https://pytorch.org/) adalah kerangka kerja *open-source* untuk *machine learning* dan *deep learning*.

# Apa yang bisa dilakukan PyTorch?

PyTorch memungkinkan pengguna untuk memanipulasi dan memproses data serta menulis algoritma *machine learning* menggunakan kode Python.

# Siapa yang menggunakan PyTorch?

Banyak perusahaan teknologi terbesar di dunia seperti [Meta (Facebook)](https://ai.facebook.com/blog/pytorch-builds-the-future-of-ai-and-machine-learning-at-facebook/), Tesla, dan Microsoft, serta perusahaan riset kecerdasan buatan seperti [OpenAI menggunakan PyTorch](https://openai.com/blog/openai-pytorch/) untuk mendukung penelitian dan menghadirkan *machine learning* pada produk mereka.

![PyTorch digunakan di berbagai industri dan penelitian](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-being-used-across-research-and-industry.png)

Sebagai contoh, Andrej Karpathy (kepala AI di Tesla) telah memberikan beberapa presentasi ([PyTorch DevCon 2019](https://youtu.be/oBklltKXtDE), [Tesla AI Day 2021](https://youtu.be/j0z4FweCy4M?t=2904)) tentang bagaimana Tesla menggunakan PyTorch untuk mendukung model *computer vision* pada sistem penglihatan komputer mereka.

PyTorch juga digunakan di industri lain seperti pertanian untuk [mendukung visi komputer pada traktor](https://medium.com/pytorch/ai-for-ag-production-machine-learning-for-agriculture-e8cfdb9849a1).

# Mengapa menggunakan PyTorch?

Hingga Februari 2022, PyTorch adalah [kerangka kerja *deep learning* yang paling banyak digunakan di Papers With Code](https://paperswithcode.com/trends), sebuah situs web untuk melacak makalah penelitian *machine learning* dan repositori kode yang terkait dengannya.

PyTorch juga membantu menangani banyak hal seperti akselerasi GPU (membuat kode berjalan lebih cepat) di balik layar.

Sehingga pengembang dapat fokus pada manipulasi data dan menulis algoritma, dan PyTorch akan memastikan agar berjalan dengan cepat.

Dan jika perusahaan seperti Tesla dan Meta (Facebook) menggunakannya untuk membangun model yang mereka terapkan untuk menggerakkan ratusan aplikasi, mengemudikan ribuan mobil, dan menyampaikan konten kepada miliaran orang, jelas mampu di sisi pengembangan juga.

# Pembahasan modul

Secara khusus, dalam modul ini akan membahas:

| **Topik** | **Isi** |
| ----- | ----- |
| **Pengenalan tentang tensor** | Tensor adalah blok bangunan dasar dari semua *machine learning* dan *deep learning*. |
| **Membuat tensor** | Tensor dapat mewakili hampir semua jenis data (gambar, kata-kata, tabel angka). |
| **Mendapatkan informasi dari tensor** | Jika Anda dapat memasukkan informasi ke dalam suatu tensor, Anda juga akan ingin mendapatkannya. |
| **Memanipulasi tensor** | Algoritma *machine learning* (seperti jaringan saraf) melibatkan manipulasi tensor dengan berbagai cara seperti penambahan, perkalian, penggabungan. |
| **Menangani bentuk tensor** | Salah satu masalah paling umum dalam *machine learning* adalah menangani ketidakcocokan bentuk (mencoba menggabungkan tensor dengan bentuk yang salah dengan tensor lain). |
| **Indexing pada tensor** | Jika Anda telah mengindeks pada daftar Python atau array NumPy, ini sangat mirip dengan tensor, kecuali mereka dapat memiliki dimensi yang jauh lebih banyak. |
| **Mencampur tensor PyTorch dan NumPy** | PyTorch bermain dengan tensor ([`torch.Tensor`]

## Importing PyTorch

Kode `import torch` dan `torch.__version__` digunakan untuk mengimpor PyTorch dan memeriksa versi yang digunakan.

In [1]:
import torch
torch.__version__

'2.1.0+cu121'

## Introduction to tensors

**Tensors** merupakan blok dasar fundamental dalam machine learning yang berfungsi untuk merepresentasikan data dalam bentuk numerik. Sebagai contoh, kita bisa merepresentasikan gambar sebagai tensor dengan bentuk `[3, 224, 224]`, yang berarti `[colour_channels, height, width]`. Artinya, gambar memiliki `3` saluran warna (merah, hijau, biru), tinggi `224` piksel, dan lebar `224` piksel.


![example of going from an input image to a tensor representation of the image, image gets broken down into 3 colour channels as well as numbers to represent the height and width](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-tensor-shape-example-of-image.png)

Dalam bahasa tensor (bahasa yang digunakan untuk mendeskripsikan tensor), tensor tersebut akan memiliki tiga dimensi, masing-masing untuk `colour_channels`, `height`, dan `width`.


### Creating tensors

1. **Scalar (Skalar):**
   - Sebuah angka tunggal.
   - Dalam tensor-speak, ini adalah tensor dimensi nol.
   - Representasinya menggunakan `torch.tensor(7)`.

2. **Vector (Vektor):**
   - Tensor satu dimensi yang dapat berisi banyak angka.
   - Misalnya, vektor `[3, 2]` bisa mewakili `[kamar_tidur, kamar_mandi]`.
   - Representasinya menggunakan `torch.tensor([7, 7])`.
   - Memiliki satu dimensi (diketahui dari jumlah tanda kurung siku `[]`).

3. **NDim dan Item:**
   - `ndim` memberikan informasi tentang jumlah dimensi suatu tensor.
   - `item()` digunakan untuk mengambil nilai Python dari tensor.
   - Contoh penggunaan pada skalar: `scalar.ndim` dan `scalar.item()`.

4. **Shape (Bentuk):**
   - Attribut yang memberikan informasi tentang bagaimana elemen-elemen di dalamnya disusun.
   - Pada vektor, bentuknya diberikan oleh `vector.shape`, dan dalam contoh di atas, menghasilkan `torch.Size([2])`.

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
# Check the number of dimensions of vector
vector.ndim

1

In [7]:
# Check shape of vector
vector.shape

torch.Size([2])

1. **Matrix (Matriks):**
   - Tensor dua dimensi yang fleksibel seperti vektor, tetapi dengan satu dimensi ekstra.
   - Representasinya menggunakan `torch.tensor([[7, 8], [9, 10]])`.
   - Memiliki dua dimensi (diketahui dari jumlah tanda kurung siku `[]`).

2. **Cek Dimensi dan Bentuk:**
   - Jumlah dimensi suatu tensor dapat diperiksa dengan menggunakan `ndim`.
   - Bentuk dari suatu tensor dapat diperoleh dengan menggunakan `shape`.
   - Contoh penggunaan pada MATRIX: `MATRIX.ndim` dan `MATRIX.shape` menghasilkan bentuk `torch.Size([2, 2])`.

3. **Tensor:**
   - Tensor dapat memiliki lebih dari dua dimensi.
   - Representasinya menggunakan `torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])`.

In [8]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
# Check number of dimensions
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [13]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

1. **Dimensi dan Bentuk Tensor:**
   - Untuk mendapatkan jumlah dimensi suatu tensor, kita dapat menggunakan `ndim`.
   - Bentuk dari suatu tensor dapat diperoleh dengan menggunakan `shape`.
   - Contoh pada tensor `TENSOR`: `TENSOR.ndim` menghasilkan `3` dan `TENSOR.shape` menghasilkan `torch.Size([1, 3, 3])`.

2. **Pemahaman Singkat:**
   - Scalar: Sebuah angka tunggal.
   - Vector: Sebuah array satu dimensi dari angka.
   - Matrix: Sebuah array dua dimensi dari angka.
   - Tensor: Sebuah array n-dimensi dari angka, di mana n bisa berapa saja.
   - Notasi umum: Skalar dan vektor biasanya ditulis dengan huruf kecil, sedangkan matriks dan tensor dengan huruf besar.
   
3. **Tabel Ringkas:**
   | Nama    | Apa itu?                                   | Jumlah Dimensi | Contoh Notasi |
   | ------- | ------------------------------------------ | --------------- | ------------- |
   | Scalar  | Sebuah angka tunggal                       | 0               | Lower (`a`)   |
   | Vector  | Sebuah array satu dimensi dari angka       | 1               | Lower (`y`)   |
   | Matrix  | Sebuah array dua dimensi dari angka        | 2               | Upper (`Q`)   |
   | Tensor  | Sebuah array n-dimensi dari angka           | Bisa berapa saja| Upper (`X`)   |

   ![scalar vector matrix tensor and what they look like](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

### Random tensors

Pembuatan tensor dengan angka acak menggunakan `torch.rand()` dapat dilihat sebagai berikut:

1. **Pembuatan Tensor dengan Angka Acak:**
   - `torch.rand(size=(3, 4))` digunakan untuk membuat tensor dengan nilai acak yang memiliki ukuran tertentu.
   - Parameter `size` menentukan bentuk atau dimensi dari tensor yang akan dibuat, contoh: `(3, 4)`.
   - Contoh penggunaan: `random_tensor = torch.rand(size=(3, 4))`.

2. **Ukuran Tensor yang Fleksibel:**
   - `torch.rand()` dapat digunakan dengan ukuran yang disesuaikan, misalnya, untuk menciptakan tensor yang merepresentasikan gambar dengan bentuk umum [224, 224, 3] ([tinggi, lebar, saluran warna]).
   - Contoh penggunaan: `random_image_size_tensor = torch.rand(size=(224, 224, 3))`.

Dengan menggunakan poin-poin di atas, kita dapat membuat tensor dengan angka acak sesuai dengan ukuran yang dibutuhkan, yang seringkali merupakan langkah awal dalam pembangunan model machine learning.

In [14]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.4043, 0.8834, 0.9275, 0.8074],
         [0.6551, 0.9651, 0.4101, 0.0596],
         [0.5910, 0.5900, 0.6019, 0.4714]]),
 torch.float32)

In [15]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

1. **Tensor dengan Nilai Nol:**
   - `torch.zeros(size=(3, 4))` digunakan untuk membuat tensor dengan semua nilai nol.
   - Parameter `size` menentukan bentuk atau dimensi dari tensor yang akan dibuat, contoh: `(3, 4)`.
   - Contoh penggunaan: `zeros = torch.zeros(size=(3, 4))`.

2. **Tensor dengan Nilai Satu:**
   - `torch.ones(size=(3, 4))` digunakan untuk membuat tensor dengan semua nilai satu.
   - Parameter `size` menentukan bentuk atau dimensi dari tensor yang akan dibuat, contoh: `(3, 4)`.
   - Contoh penggunaan: `ones = torch.ones(size=(3, 4))`.

Dengan menggunakan poin-poin di atas, kita dapat membuat tensor dengan nilai nol atau satu sesuai dengan bentuk atau dimensi yang diinginkan. Hal ini sering digunakan dalam situasi seperti masking pada model deep learning.

In [16]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [17]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating a range and tensors like

1. **`torch.arange` untuk Rentang Angka:**
   - `torch.arange(start, end, step)` digunakan untuk membuat rentang angka dengan parameter:
     - `start`: awal rentang (contoh: 0),
     - `end`: akhir rentang (contoh: 10),
     - `step`: langkah antar nilai (contoh: 1).
   - Contoh penggunaan: `torch.arange(start=0, end=10, step=1)`.

2. **Tensor dari Rentang 0 hingga 10:**
   - `zero_to_ten = torch.arange(start=0, end=10, step=1)` digunakan untuk membuat tensor dengan nilai dari 0 hingga 10.
   - `zero_to_ten_deprecated` menggunakan `torch.range()` yang sudah tidak direkomendasikan dan dapat menimbulkan error di masa depan.

3. **Tensor dari Nilai Nol dengan Bentuk Sama:**
   - `torch.zeros_like(input=zero_to_ten)` membuat tensor yang berisi nilai-nol dengan bentuk yang sama seperti tensor `zero_to_ten`.
   - Hal serupa dapat dilakukan dengan `torch.ones_like(input)` untuk membuat tensor dengan nilai satu.

In [18]:
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

<ipython-input-18-a404776195c1>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Potongan kode di bawah membahas berbagai jenis tipe data tensor yang tersedia dalam PyTorch dan bagaimana cara membuat tensor dengan tipe data tertentu.

1. **Jenis Tipe Data Tensor:**
   - Ada berbagai jenis tipe data tensor dalam PyTorch, termasuk untuk CPU dan GPU.
   - Tipe data umumnya terdiri dari `torch.float32` atau `torch.float` (32-bit floating point), `torch.float16` atau `torch.half` (16-bit floating point), dan `torch.float64` atau `torch.double` (64-bit floating point).
   - Selain itu, terdapat tipe data integer dengan berbagai presisi seperti 8-bit, 16-bit, 32-bit, dan 64-bit.

2. **Presisi dalam Komputasi:**
   - Presisi merujuk pada sejauh mana detail digunakan untuk menggambarkan suatu angka.
   - Semakin tinggi nilai presisi (8, 16, 32), semakin banyak detail dan data yang digunakan untuk menyatakan suatu angka.
   - Dalam komputasi numerik dan deep learning, presisi berpengaruh pada seberapa detail operasi-operasi matematika dapat dijalankan.

3. **Pembuatan Tensor dengan Tipe Data Tertentu:**
   - Tipe data default untuk tensor adalah `torch.float32`.
   - Dapat membuat tensor dengan tipe data tertentu menggunakan parameter `dtype` pada fungsi `torch.tensor`.
   - Tipe data dapat mencakup float (32-bit, 16-bit, 64-bit) dan integer (8-bit, 16-bit, 32-bit, 64-bit).

Dalam konteks machine learning, pemilihan tipe data dan manipulasi perangkat (device) menjadi penting karena dapat mempengaruhi performa dan kecepatan operasi-operasi pada tensor.

In [20]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [21]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

## Getting information from tensors

Tiga atribut tensor yang sering digunakan untuk mendapatkan informasi tentang tensor, yaitu `shape`, `dtype`, dan `device`. Berikut adalah penjelasannya:
1. **`shape`:**
   - Atribut ini memberikan informasi tentang bentuk (shape) tensor, yaitu berapa dimensi dan panjang setiap dimensinya.
   - Misalnya, jika tensor memiliki bentuk (3, 4), itu berarti tensor tersebut memiliki dua dimensi, dengan panjang dimensi pertama 3 dan panjang dimensi kedua 4.

2. **`dtype`:**
   - Atribut ini memberikan informasi tentang tipe data (datatype) elemen-elemen dalam tensor.
   - Contoh tipe data termasuk `torch.float32`, `torch.float16`, dan sebagainya, yang menunjukkan apakah tensor menyimpan bilangan real 32-bit, 16-bit, dll.

3. **`device`:**
   - Atribut ini memberikan informasi tentang perangkat (device) di mana tensor disimpan.
   - Perangkat dapat berupa CPU atau GPU. Jika tidak disebutkan, defaultnya adalah CPU.
   


In [22]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.0771, 0.4763, 0.4377, 0.0843],
        [0.8778, 0.6068, 0.8421, 0.8699],
        [0.7431, 0.2433, 0.3430, 0.3931]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulating tensors (tensor operations)

Dalam deep learning, data seperti gambar, teks, video, audio, struktur protein, dan sebagainya, direpresentasikan sebagai tensor. Sebuah model belajar dengan menyelidiki tensor-tensor tersebut dan melakukan serangkaian operasi (bisa mencapai ribuan atau lebih) pada tensor untuk membuat representasi pola dalam data masukan.

Operasi-operasi ini diantaranya:
- Penambahan (Addition)
- Pengurangan (Substraction)
- Perkalian (element-wise) (Multiplication)
- Pembagian (Division)
- Perkalian matriks (Matrix multiplication)

Dan itulah dasar-dasar pembangunan jaringan saraf (neural networks). Dalam konteks deep learning, neural networks menggunakan operasi-operasi ini untuk mengubah dan memanipulasi data masukan sehingga dapat memahami dan mempelajari pola-pola yang ada. Setiap operasi ini memiliki peranannya masing-masing dalam membantu neural networks memahami dan mengekstraksi fitur-fitur penting dari data.

### Basic operations

Beberapa operasi dasar pada tensor dalam PyTorch, seperti penambahan (+), pengurangan (-), dan perkalian (*).

1. **Penambahan, Pengurangan, dan Perkalian:**
   - Dapat melakukan operasi penambahan, pengurangan, dan perkalian pada tensor menggunakan operator matematika standar.
   - Contoh: Membuat tensor `[1, 2, 3]` dan menambahkannya dengan angka 10 (`tensor + 10`), serta mengalikannya dengan 10 (`tensor * 10`).

2. **Reassign vs Non-Reassign:**
   - Nilai dalam tensor tidak berubah kecuali diassign kembali. Meskipun operasi penambahan dan perkalian dilakukan, nilai dalam tensor tidak berubah kecuali tensor diassign kembali.

3. **Reassign Tensor:**
   - Misalnya, melakukan pengurangan dan assignment ulang tensor (`tensor = tensor - 10`), serta penambahan dan assignment ulang tensor (`tensor = tensor + 10`).

4. **Penggunaan Fungsi PyTorch:**
   - PyTorch menyediakan fungsi bawaan seperti `torch.mul()` (singkatan dari multiplication) dan `torch.add()` untuk melakukan operasi dasar.
   - Contoh: Menggunakan fungsi `torch.multiply(tensor, 10)` untuk melakukan perkalian pada tensor.

5. **Penggunaan Operator dan Fungsi:**
   - Meskipun terdapat fungsi PyTorch bawaan, lebih umum menggunakan simbol operator matematika seperti `*` untuk perkalian daripada fungsi seperti `torch.mul()`.

6. **Perkalian Elemen-wise:**
   - Operasi `tensor * tensor` merupakan perkalian elemen-wise, di mana setiap elemen pada indeks yang sama dikalikan.

Melalui operasi dasar ini, tensor dapat dimanipulasi untuk membentuk representasi data yang diperlukan dalam konteks pengembangan model machine learning.

In [23]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [24]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [25]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [26]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [27]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [28]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [29]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

In [30]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### Matrix multiplication (is all you need)

Operasi perkalian matriks dalam konteks pengembangan model machine learning menggunakan PyTorch.

1. **Operasi Perkalian Matriks dalam PyTorch:**
   - PyTorch menyediakan fungsionalitas perkalian matriks melalui metode `torch.matmul()`.
   - Aturan utama dalam perkalian matriks:
     - Dimensi dalam (inner dimensions) harus sesuai.
     - Matriks hasil memiliki bentuk dari dimensi luar (outer dimensions).

2. **Contoh Penggunaan:**
   - Membuat tensor `tensor` dengan bentuk `(1, 2, 3)`.

3. **Perbedaan Antara Perkalian Elemen-wise dan Perkalian Matriks:**
   - Perkalian elemen-wise melibatkan perkalian setiap elemen pada posisi yang sama.
   - Perkalian matriks melibatkan jumlah hasil perkalian elemen pada setiap baris dan kolom.

4. **Operasi Matrix Multiplication:**
   - Menggunakan operator `*` untuk perkalian elemen-wise (`tensor * tensor`).
   - Menggunakan `torch.matmul()` untuk perkalian matriks (`torch.matmul(tensor, tensor)`).
   - Menggunakan simbol "@" untuk perkalian matriks (`tensor @ tensor`).

5. **Kecepatan Perkalian Matriks:**
   - Meskipun dapat melakukan perkalian matriks secara manual, disarankan untuk menggunakan metode `torch.matmul()`, yang lebih cepat.
   - Demonstrasi perbedaan kecepatan antara kedua pendekatan tersebut menggunakan `%time`.

Melalui operasi perkalian matriks, model machine learning dapat menggabungkan informasi dari berbagai fitur dalam data, yang merupakan operasi dasar dalam neural networks dan algoritma deep learning.

In [31]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [32]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [33]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [34]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [35]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 2.25 ms, sys: 48 µs, total: 2.3 ms
Wall time: 3.37 ms


tensor(14)

In [36]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 32 µs, sys: 7 µs, total: 39 µs
Wall time: 41.7 µs


tensor(14)

## One of the most common errors in deep learning (shape errors)

Kesalahan operasi perkalian matriks dalam konteks pengembangan model machine learning menggunakan PyTorch.

1. **Shape Mismatches dalam Perkalian Matriks:**
   - Kesalahan umum dalam deep learning adalah kesalahan bentuk (shape mismatches) pada operasi perkalian matriks.
   - Pada contoh, perkalian matriks `torch.matmul(tensor_A, tensor_B)` akan menghasilkan kesalahan karena dimensi dalam (inner dimensions) tidak sesuai.

2. **Solusi dengan Transpose:**
   - Salah satu cara untuk membuat perkalian matriks berfungsi adalah dengan melakukan transpose pada salah satu matriks.
   - Transpose dapat dilakukan menggunakan `torch.transpose(input, dim0, dim1)` atau menggunakan `.T` pada tensor.

3. **Visualisasi dan Contoh:**
   - Memperlihatkan tensor `tensor_A` dan `tensor_B`, kemudian mencoba transpose pada `tensor_B`.
   - Operasi perkalian matriks berhasil saat `tensor_B` ditranspose.
   - Menunjukkan visualisasi dengan contoh tabel operasi perkalian matriks dan visual demo.

4. **Penggunaan `torch.mm()`:**
   - `torch.mm()` merupakan singkatan dari `torch.matmul()`, dan dapat digunakan untuk melakukan operasi perkalian matriks.

5. **Demonstrasi Kecepatan:**
   - Membandingkan kecepatan perkalian matriks dengan menggunakan metode manual dan `torch.matmul()`.

In [37]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: ignored

In [38]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [39]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [40]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


You can also use [`torch.mm()`](https://pytorch.org/docs/stable/generated/torch.mm.html) which is a short for `torch.matmul()`.

In [41]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [42]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


Penjelasan di atas membahas tentang pentingnya operasi perkalian matriks dalam konteks neural networks dan bagaimana operasi ini digunakan dalam praktek dengan menggunakan PyTorch.

1. **Pentingnya Perkalian Matriks dalam Neural Networks:**
   - Neural networks banyak menggunakan operasi perkalian matriks, terutama dalam layer-layer seperti `torch.nn.Linear()`.
   - Layer linear ini melakukan perkalian matriks antara input `x` dan matriks bobot `A` (weights matrix), ditambah dengan bias `b`.

2. **Fungsi Linear Layer:**
   - Rumus matematika linear layer: \(y = x \cdot A^T + b\).
   - \(x\) adalah input ke layer.
   - \(A\) adalah matriks bobot yang awalnya berisi angka acak dan diubah selama proses pembelajaran untuk merepresentasikan pola dalam data (terdapat transposisi karena bobot matriksnya diubah).
   - \(b\) adalah nilai bias yang digunakan untuk menyesuaikan sedikit bobot dan input.
   - \(y\) adalah output, yaitu manipulasi input dengan harapan menemukan pola di dalamnya.

3. **Linear Layer dalam Praktek:**
   - Menggunakan `torch.nn.Linear()` untuk membuat layer linear dengan mengubah nilai `in_features` dan `out_features`.
   - Menampilkan input, output, dan bentuknya.
   - Demonstrasi bahwa perubahan nilai `in_features` memengaruhi bentuk output.

4. **Matrix Multiplication Reproducibility:**
   - Menggunakan `torch.manual_seed(42)` untuk membuat perkalian matriks reproduktif (nilai awal yang sama setiap kali dijalankan).


### Finding the min, max, mean, sum, etc (aggregation)

Cara untuk mengagregasi nilai dalam tensor, seperti mencari nilai maksimum, minimum, rata-rata, dan jumlah:

1. **Membuat dan Menampilkan Tensor:**
   - Membuat tensor dengan nilai dari 0 hingga 90 dengan interval 10 menggunakan `torch.arange(0, 100, 10)`.
   - Menampilkan nilai tensor yang telah dibuat.

2. **Aggregasi Nilai dalam Tensor:**
   - Menggunakan metode agregasi seperti `min()`, `max()`, `mean()`, dan `sum()` pada tensor.
   - Memperlihatkan bahwa operasi `mean()` memerlukan tensor dengan tipe data float, sehingga perlu mengonversi tipe data tensor ke `torch.float32` menggunakan `type(torch.float32).mean()`.

3. **Penggunaan Metode Agregasi dengan Torch:**
   - Menunjukkan bahwa metode-metode yang sama dapat dilakukan dengan menggunakan metode dari PyTorch, seperti `torch.max()`, `torch.min()`, `torch.mean()`, dan `torch.sum()`.



In [43]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [45]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### Positional min/max

Berikut cara menggunakan metode `torch.argmax()` dan `torch.argmin()` untuk menemukan indeks dari nilai maksimum dan minimum dalam suatu tensor.

1. **Membuat dan Menampilkan Tensor:**
   - Membuat tensor dengan nilai dari 10 hingga 90 dengan interval 10 menggunakan `torch.arange(10, 100, 10)`.
   - Menampilkan nilai tensor yang telah dibuat.

2. **Menemukan Indeks Maksimum dan Minimum:**
   - Menggunakan metode `torch.argmax()` untuk mendapatkan indeks dari nilai maksimum dalam tensor.
   - Menggunakan metode `torch.argmin()` untuk mendapatkan indeks dari nilai minimum dalam tensor.
   - Menampilkan indeks di mana nilai maksimum dan minimum terjadi dalam tensor.

In [46]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### Change tensor datatype

Berikut cara mengubah tipe data (datatype) dari suatu tensor menggunakan metode [`torch.Tensor.type(dtype=None)`].

1. **Membuat Tensor dan Memeriksa Tipe Data:**
   - Membuat tensor dengan nilai dari 10 hingga 90 dengan interval 10 menggunakan `torch.arange(10., 100., 10.)`.
   - Memeriksa tipe data (datatype) dari tensor yang telah dibuat. Secara default, tipe datanya adalah `torch.float32`.

2. **Mengubah Tipe Data Tensor:**
   - Menggunakan metode `tensor.type(torch.float16)` untuk mengubah tipe data tensor menjadi `torch.float16`.
   - Menampilkan tensor yang telah diubah tipe datanya.

3. **Tentang Tipe Data Tensor:**
   - Menyampaikan catatan bahwa berbagai tipe data tensor (seperti `torch.float32`, `torch.float16`, `torch.int8`) memiliki dampak pada presisi penyimpanan nilai dalam komputer.
   - Menyebutkan bahwa semakin kecil angka (misalnya 32, 16, 8), semakin kurang presisi komputer menyimpan nilai tersebut. Tipe data yang lebih rendah umumnya menghasilkan komputasi yang lebih cepat dan model yang lebih kecil secara keseluruhan, meskipun kurang akurat.
   - Memberikan contoh bahwa jaringan saraf berbasis mobile sering kali menggunakan bilangan bulat 8-bit untuk komputasi yang lebih cepat dan model yang lebih kecil.

In [ ]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

In [48]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [49]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

### Reshaping, stacking, squeezing and unsqueezing

Metode-metode ini berguna dalam menyesuaikan bentuk dan dimensi tensor untuk memenuhi persyaratan operasi dalam pembelajaran mendalam (deep learning), terutama dalam penggunaan operasi matriks. Selain itu, untuk mengubah bentuk atau dimensi dari tensor tanpa mengubah nilai di dalamnya.

1. **`torch.reshape(input, shape)` atau `Tensor.view(shape)`**
   - Metode ini digunakan untuk mengubah bentuk (`shape`) dari tensor `input` jika bentuknya kompatibel. Metode ini dapat digunakan sebagai `torch.reshape()` atau `Tensor.view()`.
   - `torch.reshape(input, shape)` digunakan untuk mengubah bentuk tensor.
   - `Tensor.view(shape)` mengembalikan tampilan (view) dari tensor asli dengan bentuk yang berbeda tetapi menggunakan data yang sama dengan tensor asli.

2. **`torch.stack(tensors, dim=0)`**
   - Metode ini digunakan untuk menggabungkan urutan tensor (`tensors`) sepanjang dimensi baru (`dim`). Semua tensor harus memiliki ukuran yang sama.
   - Contoh penggunaan: `torch.stack([x, x, x, x], dim=0)` untuk menumpuk tensor satu di atas yang lain.

3. **`torch.squeeze(input)` dan `torch.unsqueeze(input, dim)`**
   - `torch.squeeze(input)` digunakan untuk menyusutkan dimensi yang memiliki nilai 1 dari tensor.
   - `torch.unsqueeze(input, dim)` digunakan untuk menambah dimensi dengan nilai 1 pada indeks tertentu.
   - Contoh penggunaan: `x_reshaped.squeeze()` untuk menghilangkan dimensi tambahan dan `x_squeezed.unsqueeze(dim=0)` untuk menambah dimensi pada indeks 0.

4. **`torch.permute(input, dims)`**
   - Metode ini digunakan untuk mengubah urutan nilai sumbu pada tensor `input`.
   - Contoh penggunaan: `x_original.permute(2, 0, 1)` untuk menukar urutan sumbu menjadi 2->0, 0->1, 1->2.

Penting untuk dicatat bahwa beberapa metode, seperti `torch.view()` dan `torch.permute()`, mengembalikan tampilan (view) dari tensor asli, yang berarti jika nilai di dalam tampilan diubah, nilai asli tensor juga akan berubah.

In [50]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [51]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [52]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [53]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [54]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [55]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [56]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [57]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)


1. **Membuat Tensor:**
   - `x = torch.arange(1, 10).reshape(1, 3, 3)` menciptakan tensor berukuran (1, 3, 3).

2. **Indeks Nilai:**
   - Indeks nilai dilakukan dari dimensi luar ke dalam. Misalnya, `x[0]` mengembalikan nilai dari dimensi pertama.
   - Contoh indeks:
     - `x[0]`: Mendapatkan nilai dari dimensi pertama.
     - `x[0][0]`: Mendapatkan nilai dari dimensi pertama dan kedua.
     - `x[0][0][0]`: Mendapatkan nilai dari semua dimensi.

3. **Indeks dengan : (Colon):**
   - Menggunakan `:` untuk menyatakan "semua nilai dalam dimensi ini" dan koma (`,`) untuk menambah dimensi.
   - Contoh indeks:
     - `x[:, 0]`: Mendapatkan semua nilai dari dimensi pertama dan indeks 0 dari dimensi kedua.
     - `x[:, :, 1]`: Mendapatkan semua nilai dari dimensi pertama dan kedua, namun hanya indeks 1 dari dimensi ketiga.
     - `x[:, 1, 1]`: Mendapatkan semua nilai dari dimensi pertama, hanya indeks 1 dari dimensi kedua, dan hanya indeks 1 dari dimensi ketiga.
     - `x[0, 0, :]` (sama dengan `x[0][0]`): Mendapatkan indeks 0 dari dimensi pertama dan kedua, dan semua nilai dari dimensi ketiga.

In [58]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [59]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [60]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [61]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [62]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [63]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

## PyTorch tensors & NumPy

1. **NumPy ke PyTorch:**
   - `torch.from_numpy(ndarray)` digunakan untuk mengonversi NumPy array menjadi PyTorch tensor.
   - Misalnya, `array = np.arange(1.0, 8.0)` akan diubah menjadi tensor PyTorch dengan menggunakan `torch.from_numpy(array)`.

2. **Perhatian pada Tipe Data:**
   - Default NumPy array memiliki tipe data float64. Jika ingin mengonversi ke tensor PyTorch dengan tipe data float32, gunakan `.type(torch.float32)` setelah `torch.from_numpy(array)`.

3. **Perubahan Tensor vs. Array:**
   - Jika tensor diubah setelah pengonversian, array asli tetap tidak berubah.
   - Contoh: `array = array + 1` tidak mempengaruhi tensor yang telah dibuat.

4. **PyTorch ke NumPy:**
   - `tensor.numpy()` digunakan untuk mengonversi tensor PyTorch menjadi NumPy array.
   - Misalnya, `tensor = torch.ones(7)` akan diubah menjadi NumPy array menggunakan `tensor.numpy()`.

5. **Perubahan Tensor vs. Array (lagi):**
   - Seperti sebelumnya, jika tensor diubah, array NumPy yang baru tetap tidak berubah.
   - Contoh: `tensor = tensor + 1` tidak mempengaruhi numpy_tensor yang telah dibuat.

Dengan menggunakan fungsi-fungsi ini, maka dapat dengan mudah berpindah antara NumPy dan PyTorch sesuai dengan kebutuhan.

In [64]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [65]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [66]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [67]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

1. **Pseudorandomness dalam Komputasi:**
   - Pseudorandomness merujuk pada penggunaan algoritma untuk menciptakan rangkaian angka yang terlihat acak tetapi sebenarnya dapat diprediksi karena sifat deterministik komputer. Meskipun terdapat perdebatan, komputer pada dasarnya bersifat deterministik.

2. **Peran Pseudorandomness dalam Neural Networks:**
   - Neural networks menggunakan angka acak (pseudorandom) sebagai awal untuk menggambarkan pola dalam data. Tujuan utamanya adalah untuk meningkatkan angka-angka acak ini melalui operasi tensor untuk lebih baik menggambarkan pola dalam data.

3. **Reproducibility dalam Machine Learning:**
   - Reproducibility mengacu pada kemampuan untuk mendapatkan hasil yang sama atau sangat mirip saat menjalankan suatu kode pada komputer yang berbeda. Ini penting untuk eksperimen yang dapat diulang dan verifikasi oleh orang lain.

4. **Contoh Penerapan Reproducibility dengan PyTorch:**
   - Dua tensor acak (`random_tensor_A` dan `random_tensor_B`) dibuat tanpa pengaturan seed, sehingga nilai-nilainya berbeda.
   - Dengan menetapkan seed menggunakan `torch.manual_seed(seed)`, kita dapat membuat dua tensor acak (`random_tensor_C` dan `random_tensor_D`) yang memiliki nilai yang sama.
   - Menggunakan seed memungkinkan kita untuk memiliki tingkat kontrol dan konsistensi dalam eksperimen dan pengujian.

5. **Implementasi Reproducibility dengan PyTorch:**
   - `torch.manual_seed(seed=RANDOM_SEED)` digunakan untuk mengatur seed pada tensor acak.
   - Setelah menetapkan seed, penggunaan `torch.rand(3, 4)` akan menghasilkan tensor dengan nilai yang konsisten.
   - Penting untuk me-reset seed setiap kali fungsi `rand()` baru dipanggil untuk memastikan konsistensi.

In [68]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [69]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running tensors on GPUs (and making faster computations)

Algoritma deep learning memerlukan banyak operasi numerik. Secara default, operasi-operasi ini sering dilakukan pada CPU (unit pemrosesan komputer). Namun, terdapat sebuah perangkat keras umum yang disebut GPU (unit pemrosesan grafis), yang seringkali jauh lebih cepat dalam melakukan jenis operasi tertentu yang dibutuhkan oleh neural networks (seperti perkalian matriks) dibandingkan dengan CPU.

Terdapat beberapa cara untuk mendapatkan akses ke GPU.


### 1. Getting a GPU

Berikut adalah beberapa cara untuk mendapatkan akses ke GPU dan keuntungan serta kerugiannya:

| **Metode** | **Kesulitan Setup** | **Pro** | **Kontra** | **Cara Setup** |
| ----- | ----- | ----- | ----- | ----- |
| Google Colab | Mudah | Gratis digunakan, hampir tidak memerlukan setup, dapat berbagi pekerjaan dengan orang lain hanya dengan tautan | Tidak menyimpan output data, komputasi terbatas, rentan terhadap batas waktu | [Ikuti Panduan Google Colab](https://colab.research.google.com/notebooks/gpu.ipynb) |
| Gunakan milik pribadi | Sedang | Jalankan semuanya secara lokal di komputer sendiri | GPU tidak gratis, memerlukan biaya awal | Ikuti [Pedoman Instalasi PyTorch](https://pytorch.org/get-started/locally/) |
| Komputasi awan (AWS, GCP, Azure) | Sedang-Sulit | Biaya awal kecil, akses ke komputasi yang hampir tak terbatas | Dapat mahal jika berjalan terus menerus, memerlukan waktu untuk mengatur dengan benar | Ikuti [Pedoman Instalasi PyTorch](https://pytorch.org/get-started/cloud-partners/) |


Untuk memeriksa apakah memiliki akses ke GPU Nvidia dapat menjalankan `!nvidia-smi` di mana `!` (juga disebut dengan "bang") berarti "jalankan ini di baris perintah".

In [70]:
!nvidia-smi

Wed Jan  3 20:57:26 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

Jika tidak memiliki akses ke GPU Nvidia, output di atas akan menampilkan sesuatu seperti:

```
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

Dalam hal ini, kembali dan ikuti langkah-langkah instalasi.

Jika memiliki GPU, baris di atas akan menampilkan sesuatu seperti:

```
Wed Jan 19 22:09:08 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.46       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```



### 2. Getting PyTorch to run on the GPU

1. **Cek Ketersediaan GPU:**
   - Gunakan `torch.cuda.is_available()` untuk memeriksa apakah PyTorch dapat melihat dan menggunakan GPU.
   - Jika outputnya True, PyTorch dapat menggunakan GPU; jika False, perlu melalui langkah instalasi lagi.

2. **Menetapkan Jenis Perangkat:**
   - Tetapkan variabel `device` sebagai "cuda" jika GPU tersedia, dan "cpu" jika tidak.
   - Hal tersebut memungkinkan kode dapat berjalan baik pada CPU maupun GPU.

3. **Mengetahui Jumlah GPU:**
   - Gunakan `torch.cuda.device_count()` untuk menghitung jumlah GPU yang dapat diakses oleh PyTorch.
   - Informasi ini berguna jika ingin menjalankan suatu proses pada satu GPU tertentu atau menggunakan semua GPU.

Pastikan untuk menulis kode PyTorch yang bersifat agnostik perangkat, artinya dapat berjalan pada CPU atau GPU. Jika kecepatan komputasi yang lebih tinggi diperlukan, maka dapat menggunakan GPU, dan untuk kecepatan komputasi yang jauh lebih tinggi, maka dapat menggunakan beberapa GPU.


In [71]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [72]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [73]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

1. **Pemindahan Tensor ke Perangkat Tertentu:**
   - Gunakan `to(device)` pada tensor atau model untuk memindahkannya ke perangkat tertentu.
   - Keuntungan: GPU menawarkan komputasi numerik yang jauh lebih cepat daripada CPU.
   - Jika GPU tidak tersedia, kode yang agnostik perangkat akan tetap berjalan di CPU.

2. **Catatan Penting:**
   - Memindahkan tensor ke GPU dengan `to(device)` mengembalikan salinan tensor, sehingga tensor asli tetap ada di CPU.
   - Untuk menimpa tensor, perlu menetapkan ulang tensor tersebut, misalnya: `some_tensor = some_tensor.to(device)`.

3. **Contoh Penerapan:**
   - Buat tensor default pada CPU: `tensor = torch.tensor([1, 2, 3])`.
   - Cek perangkat tensor: `print(tensor, tensor.device)`.
   - Pindahkan tensor ke GPU jika tersedia: `tensor_on_gpu = tensor.to(device)`.

Jika GPU tersedia, tensor kedua akan memiliki perangkat 'cuda:0', menandakan bahwa tensor tersebut disimpan di GPU 0 (indeks GPU dimulai dari 0).

In [74]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

1. **Pengembalian Tensor ke CPU:**
   - Jika ingin berinteraksi dengan tensor menggunakan NumPy (karena NumPy tidak menggunakan GPU), perlu memindahkan tensor dari GPU ke CPU.
   - Metode `Tensor.cpu()` digunakan untuk mengembalikan tensor ke memori CPU.

2. **Contoh Penerapan:**
   - Menggunakan `torch.Tensor.numpy()` pada tensor_on_gpu akan menghasilkan error jika tensor berada di GPU.
   - Untuk mengembalikan tensor ke CPU, gunakan `tensor_on_gpu.cpu().numpy()`.

3. **Hasil:**
   - Hasil dari `tensor_on_gpu.cpu().numpy()` adalah salinan tensor yang awalnya ada di GPU, dan tensor asli masih tetap berada di GPU.

In [75]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: ignored

In [76]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [77]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')